version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET_KET=${JWT_SECRET_KEY}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - VNPAY_CODE=${VNPAY_CODE}
      - VNPAY_SECRET=${VNPAY_SECRET}
      - VNPAY_URL=${VNPAY_URL}
    networks:
      - spss-network
    # depends_on:
    #   - postgres # Đảm bảo mysql được khởi động trước
    restart: always
  # postgres:
  #   image: postgres:16 # Chọn phiên bản PostgreSQL 16
  #   container_name: spss_postgres
  #   environment:
  #     - POSTGRES_DB=spssdb
  #     - POSTGRES_USER=spss
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "15433:5432"
  #   networks:
  #     - spss-network
  #   restart: always

networks:
  spss-network:
    driver: bridge
