version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/spss
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - spss-network
    depends_on:
      - mysql # Đảm bảo mysql được khởi động trước
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - spss-network
    restart: always
  mysql:
    image: mysql:lts
    container_name: mysql
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: spss
    ports:
      - "3306:3306"
    #    volumes:
    #      - ./data/mysql:/var/lib/mysql/data
    networks:
      - spss-network
    restart: always

networks:
  spss-network:
    driver: bridge
