version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET_KET=${JWT_SECRET_KEY}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - VNPAY_CODE=${VNPAY_CODE}
      - VNPAY_SECRET=${VNPAY_SECRET}
      - VNPAY_URL=${VNPAY_URL}
    networks:
      - spss-network
    # depends_on:
    #   - mysql # Đảm bảo mysql được khởi động trước
    restart: always
  # mysql:
  #   image: mysql:lts
  #   container_name: mysql
  #   # set shared memory limit when using docker-compose
  #   shm_size: 128mb
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: spss
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - spss-network
  #   restart: always

networks:
  spss-network:
    driver: bridge
