spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  app:
    jwtSecret: ${JWT_SECRET_KEY}
    jwtExpirationMs: 172800000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

frontend-url: http://localhost:5173

# cloudinary
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

# vnpay
payment:
  vnPay:
    url: ${VNPAY_URL}
    tmnCode: ${VNPAY_CODE}
    secretKey: ${VNPAY_SECRET}
    returnUrl: http://localhost:8080/api/payment/vnpay-callback
